import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./reset.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DropZone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${roboto.variable} antialiased flex flex-col min-h-dvh`}>
            {children}
        </body>
        </html>
    );
}
